---
name: waterpotability

volumes:
  mosquitto:
  influxdb:

networks:
  internal:

services:
  backend:
    build:
      context: ..
    restart: unless-stopped
    networks:
      - internal
    environment:
      CONFIG_FILEPATH: /tmp/config.json
    volumes:
      - ../config.json:/tmp/config.json:ro

  influxdb:
    image: influxdb:2.7.10-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    networks:
      - internal
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME?:error}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD?:error}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG?:error}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET?:error}
    healthcheck:
      test: influx ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
