# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
name: waterpotability

volumes:
  mosquitto:
  influxdb:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20-openssl
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./passwd:/mosquitto/config/passwd:ro
    ports:
      - 1883:1883
    # ref: https://github.com/eclipse-mosquitto/mosquitto/issues/1270#issuecomment-1476038461
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-u", "icn", "-P", "admin", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  influxdb:
    image: influxdb:2.7.10-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: icn
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: icn
      DOCKER_INFLUXDB_INIT_BUCKET: wp
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    healthcheck:
      test: influx ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

