# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  api:
    build: ..
    environment:
      INFLUXDB_PROTOCOL: ${INFLUXDB_PROTOCOL:?error}
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME:?error}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD:?error}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN:?error}
      INFLUXDB_ORG: ${INFLUXDB_ORG:?error}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET:?error}
      MQTT_PROTOCOL: ${MQTT_PROTOCOL:?error}
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID:?error}
      MQTT_USERNAME: mirzaganteng
      MQTT_PASSWORD: admin
    depends_on:
      mosquitto:
        condition: service_healthy
        restart: true
      influxdb:
        condition: service_healthy
        restart: true

